apiVersion: v1
kind: Pod
metadata:
  name: lagoserv-pod
spec:
  containers:
    - name: lagoserv-container
      image: asia-northeast3-docker.pkg.dev/lagoon-1/docker-registry/lagoserv:latest
      ports:
        - containerPort: 50051
      env:
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "admin!"
        - name: DB_HOST
          value: "35.239.148.252" # Cloud SQL 인스턴스의 연결 주소
        - name: DB_NAME
          value: "postgres"
        - name: INSTANCE_CONNECTION_NAME
          value: "lagoon-1:us-central1:lagoon"
        - name: DB_PORT
          value: "5432" # 기본적으로 MySQL은 3306, PostgreSQL은 5432