apiVersion: v1
kind: Service
metadata:
  name: lagoserv-service
spec:
  selector:
    app: lagoserv-server
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
  type: LoadBalancer
